### ISSUE TITLE
[BUG] [V.11.315] the tab does not appear on Tidy sheet

### ISSUE THREAD

**Issue by Dalkan75** [p4535992/foundryvtt-downtime-dnd5e#17]
Hello,
as per the title, the tab on the tidy cards does not appear while the basic D&D tab does.
Maybe it no longer works on V11 but on V12 it does? (I'm waiting at least another month before migrating).
Thanks for any solutions.

![Cattura](https://github.com/p4535992/foundryvtt-downtime-dnd5e/assets/108159546/f0222323-41ba-451c-92c8-4641545836e1)

**Comment by imivoltz** [comment]
I'm on v12 but give this a try;
Go into the sheet tab selection settings here by clicking the 3 dots next to the character level:
![image](https://github.com/p4535992/foundryvtt-downtime-dnd5e/assets/74024189/c19c5ece-6de2-4d2e-b0b6-a9647b82d46e)
See if Downtime appears in the available tabs section, if it does, put it on the selected tabs section.
![image](https://github.com/p4535992/foundryvtt-downtime-dnd5e/assets/74024189/7f071692-a17b-424d-af57-5f0aa2fb2b69)

**Comment by Dalkan75** [comment]
Thanks so much, I hadn't noticed, it actually works :)
