### ISSUE TITLE
Feature request - Edit/import lock for players

### ISSUE THREAD

**Issue by lucaspicerni** [p4535992/foundryvtt-downtime-dnd5e#2]
Would it be possible to implement an option to hide buttons (such as import, export, and even edit and delete categories and activities buttons) from players? Or maybe some integration with the [Tidy5e sheet](https://github.com/sdenec/tidy5e-sheet) or [Illandril's Character Sheet Lockdown](https://github.com/illandril/FoundryVTT-sheet5e-lockdown), so these options don't show up when the sheet is locked? Thank you!

**Comment by p4535992** [comment]
Is been a while, but the module setting "Enable GM Only Edit Mode." should be do that. Did you try it ?

**Comment by lucaspicerni** [comment]
My apologies, I missed it completely! I tested it and it works perfectly, thank you!
