### ISSUE TITLE
[BUG] ReferenceError: getMacroAsync is not defined

### ISSUE THREAD

**Issue by SemBerretty** [p4535992/foundryvtt-downtime-dnd5e#20]
Macro noob here trying to get a macro to work to increase the downtime progress with the number rolled. I've been using one of the example macros(which I had to alter since it also gave errors). The macro itself adds progress, but I cant add it to the downtime activity because it comes up with errors trying to access it.

The downtime item:
![image](https://github.com/p4535992/foundryvtt-downtime-dnd5e/assets/16963487/25c34b21-6882-46ff-8896-a8c16cf576d6)

The macro:
![image](https://github.com/p4535992/foundryvtt-downtime-dnd5e/assets/16963487/13e2ab32-fd7e-4454-b37d-79e065cff5b6)

The error:
![image](https://github.com/p4535992/foundryvtt-downtime-dnd5e/assets/16963487/f7f92bbd-779d-441a-baec-8953f3696b35)

I might not be adding the correct name/ID to the relevant field, but I tried the name and the UUID and both gave the same error.

**Browser:**
 Chrome

**Foundry Version:** 
Version 12 - 327
**Game System:** 
D&D 5e 3.2.1

**Comment by Dejsving** [comment]
upload your macro via the macros menu using the export menu and attach it - I'll look at it and try to help you

**Comment by SemBerretty** [comment]
> upload your macro via the macros menu using the export menu and attach it - I'll look at it and try to help you

Sorry for the late reply. I really don't think its a macro issue. The issue is when I add the UUID of the macro to the downtime item and try to click the downtime item which should run the macro. This is not happening due to the error I referenced.

**Comment by Dejsving** [comment]
I checked your mistake with myself. It doesn't work either. The fact is that the author used the runMacroOnExplicitActor method, which is not defined in Foundry. I do not know the reason.
But you can cure it like this:
in the FoundaryData/Data/modules/downtime file-dnd5e/module.js you need to replace the line
runMacroOnExplicitActor(actor, macro, macroData); number 2067
with the line
macro.execute();
and everything will work for you.

**Comment by p4535992** [comment]
Should be fixed on 1.3.8 sorry for the delay
