### ISSUE TITLE
Compatibility Request - KGar's TidySheet5e

### ISSUE THREAD

**Issue by KonteiKeisei** [p4535992/foundryvtt-downtime-dnd5e#5]
Just throwing this here as the new Tidy is happening, currently in alpha, and if Tidy based compatibility is to be maintained, that's where it would need to live to continue?

Assuming this will have to wait until at least a beta release on that module, but wanted to throw it here for backlog/to-do if there's something that needs to be done on this end.

**Comment by kgar** [comment]
I've now started work today on compatibility for this module. Hoping to have good news before long.

**Comment by kgar** [comment]
Almost ready with an initial offering. I have a few more things to do on the Tidy side, and then I will be able to submit my PR on this side 🤞
